baseURL = 'https://bibliothequelibre.ch/'
languageCode = 'ch-fr'
title = 'Bibliothèque Libre'
#theme = "biblioTheme"

[menu]
[[menu.main]]
name = "Accueil"
url = "/"
weight = 1
[[menu.main]]
name = "Agenda"
url = "/agenda/"
weight = 2
[[menu.main]]
name = "Livres"
url = "/livres/"
weight = 3
[[menu.main]]
name = "Accès"
url = "/acces/"
weight = 4
[[menu.main]]
name = "Photos et archives"
url = "/photos-archives/"
weight = 5
