baseURL = 'http://example.org/'
languageCode = 'ch-fr'
title = 'Bibliothèque Libre'
#theme = "biblioTheme"

[menu]
[[menu.main]]
name = "Accueil"
url = "/"
weight = 1
[[menu.main]]
name = "A Propos"
url = "/apropos/"
weight = 2
[[menu.main]]
name = "Livres"
url = "/livres/"
weight = 3