# github does some weird stuff and created a workflow called "pages build and deployment" when "deploy from a branch"
# is selected in Settings -> Pages.
# it targets the `gh-pages` branch and deploys from there automatically

name: build-hugo-and-push-gh-pages

on:
  push:
    branches:
      - main

  # Allows to run workflow manually from Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.111.3"
          extended: true

      - name: Build Hugo
        run: hugo --minify

      # this task automatically pushes the ./public contents to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public